### ISSUE TITLE
set attribute error

### ISSUE THREAD

**Issue by hassin23ayz** [dCache/nfs4j#83]
Hello I am encountering this problem what might be the reason ? 

2019-10-10 01:14:11.794 [] [nfs@2049 (8)] ERROR o.d.n.v.NfsServerV3 - SETATTR
java.lang.IllegalArgumentException: Illegal mode "w" must be one of "r", "rw", "rws", or "rwd"
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:239)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at org.dcache.simplenfs.LocalFileSystem.setattr(LocalFileSystem.java:527)
	at org.dcache.nfs.vfs.PseudoFs.setattr(PseudoFs.java:326)
	at org.dcache.nfs.v3.HimeraNfsUtils.set_sattr(HimeraNfsUtils.java:167)
	at org.dcache.nfs.v3.NfsServerV3.NFSPROC3_SETATTR_3(NfsServerV3.java:1159)
	at org.dcache.nfs.v3.xdr.nfs3_protServerStub.dispatchOncRpcCall(nfs3_protServerStub.java:55)
	at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kofemann** [comment]
this is bug in simple-nfs. closing here.

**Comment by kofemann** [comment]
Please use updated version of simple-nfs
